config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  # get 'production_companies/index'
  # get 'production_companies/show'
  # get 'movies/index'
  # get 'movies/show'
  resources :movies, only: [:index, :show]
  resources :production_companies, only: [:index, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :production_company

  validates :title, :year, :duration, :description, :average_vote, presence: true
  validates :title, uniqueness: true
  validates :year, :duration, numericality: { only_integers: true }
  validates :average_vote, numericality: true
end

app/models/production_company.rb
class ProductionCompany < ApplicationRecord
  has_many :movies

  validates :name, uniqueness: true

  def self.ordered_by_movies
    self.select('production_companies.*')
        .select('COUNT(production_companies.id) as movie_count')
        .left_joins(:movies)
        .group('production_companies.id')
        .order('movie_count DESC')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @movies = Movie.includes(:production_company)
    .order("average_vote DESC")
    .limit(10)

    @production_companies = ProductionCompany.limit(10)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # Show all data on movies' page
  def index
    # this create N + 1 problem
    # +1 refers to movies whereas N refers to production_companies
    # in short this means we are reduntantly calling the databse which can be expensive :)
    # @movies = Movie.all
    @movies = Movie.includes(:production_company).all.order('average_vote DESC')
  end

  # show single data on each movie's page
  def show
    @movie = Movie.find(params[:id])
  end
end

app/controllers/production_companies_controller.rb
class ProductionCompaniesController < ApplicationController
  def index
     # all production companies
     #@production_companies = ProductionCompany.all

    #  @production_companies = ProductionCompany.select('production_companies.*')
    #                       .select('COUNT(production_companies.id) as movie_count')
    #                       .left_joins(:movies)
    #                       .group('production_companies.id')
    #                       .order('movie_count DESC')

    @production_companies = ProductionCompany.ordered_by_movies
    #.limit(10)
  end

  def show
    # a specific production company
    @production_company = ProductionCompany.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/production_companies_helper.rb
module ProductionCompaniesHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>

<div class="columns">
  <div class="column">
    <h2 class="title is-2">Top 10 Movies</h2>
      <ol class="ml-5">
        <% @movies.each do |movie| %>
          <li>
            <%= link_to movie.title, movie %> <em>(<%= movie.production_company.name %>)</em>
          </li>
        <% end %>
      </ol>
      <p class="mt-5">
        <strong>
          <%= link_to '🌭 see all movies', movies_path%>
        </strong>
      </p>
  </div>

  <div class="column">
    <h2 class="title is-2">Top 10 Production Companies</h2>
    <ol class="ml-5">
      <% @production_companies.each do |production_company| %>
        <li>
          <%= link_to production_company.name, production_company %>
        </li>
      <% end %>
    </ol>
    <p class="mt-5">
      <strong>
        <%= link_to '🎬 For more Production Companies', production_companies_path%>
      </strong>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:html_title) + "-" if content_for?(:html_title) %>Top 100 Movies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  </head>

  <body>
    <section class="section">
      <div class="container">
        <h1 class="title is-1">Top movies From IMDB</h1>
      </div>
      <%= yield %>
    </section>
  </body>
</html>

app/views/movies/_movie.html.erb
<h2 class="title is-2">
  <%= @movie.title %>
</h2>

<article class="message is-dark">
  <div class="message-header">
    <p>Description</p>
  </div>
  <div class="message_body">
    <%= @movie.description %>
  </div>
</article>

<progress class="progress is-info" value="<%= @movie.average_vote %>" max=10>
  <%= @movie.average_vote %>
</progress>

<p>
  <strong>Rating: </strong>
  <%= @movie.average_vote %>
</p>

<p>
  <strong>Release Year:</strong>
  <%= @movie.year %>
</p>

<p>
  <strong>Duration:</strong>
  <%= link_to @movie.duration%>
</p>

<p>
  <strong>Production Company:</strong>
  <%= link_to @movie.production_company.name, @movie.production_company %>
</p>

app/views/movies/index.html.erb
<h2 class="title is-2">Top 100 Movies</h2>

<ol class="ml-5">
  <% @movies.each do |movie| %>
    <li>
      <%= link_to movie.title, movie %> was produced by <%= link_to movie.production_company.name, movie.production_company.name%>
    </li>
  <% end %>
</ol>

app/views/movies/show.html.erb
<% content_for(:html_title){@movie.title}%>
<%= render @movie %>

app/views/production_companies/index.html.erb
<h2 class="title is-2">Production Companies</h2>
<ol>
  <% @production_companies.each do | company | %>
    <li>
      <%= link_to company.name, company%>
      <em>(<%= pluralize company.movie_count, "Top Movie" %>)</em>
    </li>
  <% end %>
</ol>

app/views/production_companies/show.html.erb
<h2 class="title is-2"><%= @production_company.name %></h2>
<p class="mb-5">
  This production company made <%= @production_company.movies.count %> of the top 100 movies.
</p>
<h3 class="title is-3">Movides made by <%= @production_company.name %></h3>
<ul>
  <% @production_company.movies.each do |movie| %>
  <li><%= link_to movie.title, movie %> with a rating of <%= movie.average_vote %></li>
  <% end %>
</ul>